Hw2
================
Hubert Chang
2026-10-06

\#Problem 0 set up

``` r
library (tidyverse)
```

    ## ── Attaching core tidyverse packages ──────────────────────── tidyverse 2.0.0 ──
    ## ✔ dplyr     1.2.1     ✔ readr     2.2.0
    ## ✔ forcats   1.0.1     ✔ stringr   1.6.0
    ## ✔ ggplot2   4.0.3     ✔ tibble    3.3.1
    ## ✔ lubridate 1.9.5     ✔ tidyr     1.3.2
    ## ✔ purrr     1.2.2     
    ## ── Conflicts ────────────────────────────────────────── tidyverse_conflicts() ──
    ## ✖ dplyr::filter() masks stats::filter()
    ## ✖ dplyr::lag()    masks stats::lag()
    ## ℹ Use the conflicted package (<http://conflicted.r-lib.org/>) to force all conflicts to become errors

``` r
library (readxl)
```

\#Problem 1

``` r
nytransit = read.csv("data/NYC_Transit_Subway_Entrance_And_Exit_Data.csv") |>
  janitor::clean_names()|>
  select (line, station_name, station_latitude, station_longitude, route1:route11, entrance_type, entry, vending, ada) |>
  
  mutate(
    entry = recode_values(
      entry,
      "YES" ~ TRUE,
      "NO" ~ FALSE
    )
  )
```

The dataset contains information on the subway line, station name, the
station’s latitude and longitude, the routes from 1 to 11, the type of
entrances, and if you can have entry, whether it has a vending machine
and if it is ada compliant. The data have 1868 observations with 19
variables. The data can be tidied up more because route 1 - 11 all have
their own column with a lot of missing data.

How many distinct stations are there? Note that stations are identified
both by name and by line (e.g. 125th St 8th Avenue; 125st Broadway;
125st Lenox); the distinct function may be useful here.

``` r
nytransit |>
  distinct(line, station_name) |>
  nrow()
```

    ## [1] 465

There are 465 distinct stations.

How many stations are ADA compliant?

``` r
nytransit |>
  distinct(line, station_name, ada) |>
  filter (ada == TRUE) |>
  nrow()
```

    ## [1] 84

84 stations are ADA compliant

What proportion of station entrances / exits without vending allow
entrance?

``` r
nytransit|>
  filter( vending == "NO" ) |>
  pull (entry) |>
  mean()
```

    ## [1] 0.3770492

About 37.70 % of the station entrance/ exits is without a vending

\#Reforming data

``` r
nytransit_clean =
  nytransit |>
  mutate (
    across (
      route1:route11, as.character)) |>
  pivot_longer(
    cols = route1:route11,
    names_to = "route_number",
    names_prefix = "route",
    values_to = "route_name"
  )
```

How many distinct stations serve the A train?

``` r
nytransit_clean |>
  filter(route_name == "A") |>
  distinct(line, station_name)|>
  nrow()
```

    ## [1] 60

60 distinct stations

Of the stations that serve the A train, how many are ADA compliant?

``` r
nytransit_clean |>
  filter(route_name == "A", ada == "TRUE") |>
  distinct(line, station_name)|>
  nrow()
```

    ## [1] 17

17 stations are ADA compliant.

\#Problem 2

Mr Trash Wheel

``` r
trashwheel =
  read_excel("data/202610 Trash Wheel Collection Data.xlsx",
            sheet = "Mr. Trash Wheel",
            range = cell_cols("A:N"),
            skip = 1,
            na = c("NA", ".", "") 
            ) |>
  janitor :: clean_names() |>
  drop_na(dumpster) |>
  mutate(
    sports_balls = as.integer (
      round(sports_balls)
    )) |>
  
  mutate(
    year = as.numeric(year), wheel_name = "Mr. Trash Wheel"
  )
```

Professor Trash Wheel

``` r
profwheel = read_excel("data/202610 Trash Wheel Collection Data.xlsx",
            sheet = "Professor Trash Wheel",
            skip = 1,
            na = c("NA", ".", "") 
            ) |>
  janitor :: clean_names() |>
  drop_na(dumpster) |>

 mutate(
    year = as.numeric(year), wheel_name = "Professor Trash Wheel" 
  ) |>
  
  mutate(
    plastic_bottles = as.numeric(plastic_bottles)
  )
```

    ## Warning: There was 1 warning in `mutate()`.
    ## ℹ In argument: `plastic_bottles = as.numeric(plastic_bottles)`.
    ## Caused by warning:
    ## ! NAs introduced by coercion

Gwynnda Trash Wheel

``` r
gwynndawheel = read_excel("data/202610 Trash Wheel Collection Data.xlsx",
            sheet = "Gwynnda the Good Wheel of the W",
            skip = 1,
            na = c("NA", ".", "") 
            ) |>
  janitor :: clean_names() |>
  drop_na(dumpster) |>
  
  mutate(
    year = as.numeric(year), wheel_name = "Gwynnda"
  )
```

Combining the three

``` r
trashwheel_tidy =
  bind_rows (trashwheel, profwheel, gwynndawheel) |>
  janitor::clean_names() |>
  relocate (wheel_name)
```

The combined trash wheel have 1269 observations. It also have 15
variables. Main variables in the document contains wheel_name, dumpster,
month, year, date, weight_tons, volume_cubic_yards,
plastic_bottles,polystyrene, cigarette_butts, glass_bottles,
plastic_bags, wrappers, sports_balls, homes_powered

``` r
prof_weight = 
  trashwheel_tidy |>
  filter (wheel_name == "Professor Trash Wheel") |>
  pull (weight_tons) |>
  sum (na.rm = TRUE)
```

Professor Trash Wheel collected 295 tons

``` r
gwynnda_cig = 
  trashwheel_tidy |>
  filter(wheel_name == "Gwynnda", month == "June", year == 2022) |>
  pull(cigarette_butts) |>
  sum (na.rm = TRUE)
```

Gwynnda collected 18120 cigarette butts in June of 2022

\#Problem 3

``` r
mci_df= read.csv("data_mci/data_mci/MCI_baseline.csv",
  na = c("NA", ".", ""),
  skip = 1 
                ) |>
janitor :: clean_names() 
```

``` r
mci_data = 
  mci_df |>
  
mutate(
  sex = recode_values(
      sex,
      1 ~ "Male",
      0 ~ "Female"
    ),
  apoe4 = recode_values(
      apoe4,
      1 ~ "APOE4 Carrier",
      0 ~ "APOE4 NON-Carrier"
    )
      )  |> #converting from numbers to characters

filter(is.na(age_at_onset | age_at_onset > current_age)) #removing MCI onset before study baseline
```

The baseline file had a note above, so we have to remove that with skip
= 1, I also removed any data that had response with NA, . , or blank.
And then I recoded the values from numbers in sex and apoe4 from 1/0 to
characters (male/female) (apoe carrier or not).Lastly, I removed anyone
who had MCI onset before basline age.

``` r
mci_women = 
  mci_data |>
  filter (sex == "Female") |>
  mutate ( carrier = apoe4 == "APOE4 Carrier") |>
  pull (carrier) |>
  mean()
```

483 participants recruited and of those 97 developed MCI. The average
baseline age is 64.9049223 years old. Among the study of women about 20%
are APOE4 carriers

``` r
amyloid_df = read.csv("data_mci/data_mci/mci_amyloid.csv",
  na = c("NA", ".", ""),
  skip = 1) |>
  janitor:: clean_names() |>
  rename(id = study_id) 
```

I pulled the data from the mci_amyloid.csv file, then I removed any
missing data that had “NA”, “.”, or blank. I also had to skip the first
line because it is just headder. Then I used janitor to clean the file
and then renamed study_id to id so it matches with the baseline file.

``` r
  anti_join(mci_data, amyloid_df, by = "id") 
```

    ##    id current_age    sex education             apoe4 age_at_onset
    ## 1  92        68.6 Female        20 APOE4 NON-Carrier           NA
    ## 2 179        68.1   Male        16 APOE4 NON-Carrier           NA
    ## 3 304        63.8 Female        16 APOE4 NON-Carrier           NA
    ## 4 389        59.3 Female        16 APOE4 NON-Carrier           NA
    ## 5 412        67.0   Male        16     APOE4 Carrier           NA

There are 5 people that are in baseline list but not amyloid

``` r
  anti_join(amyloid_df, mci_data, by = "id")
```

    ##      id    baseline      time_2      time_4      time_6      time_8
    ## 1     3 0.106087034 0.108744509 0.106065035        <NA> 0.106152357
    ## 2     5 0.107950408 0.112273883 0.115139677 0.106606054 0.106052066
    ## 3     7 0.112246391        <NA> 0.104251905 0.112485583 0.112055612
    ## 4    13 0.110300505 0.108534417 0.108100808 0.109229662 0.104861901
    ## 5    18 0.114137255 0.107093264 0.110872562 0.108982605 0.106873903
    ## 6    22 0.109320501        <NA> 0.107524961 0.106098161 0.105416197
    ## 7    26 0.104749004 0.110171403 0.106128029 0.102036973 0.104994305
    ## 8    30 0.109311868 0.111327152 0.107454368 0.113914306 0.108895642
    ## 9    39 0.104426255        <NA> 0.103901084 0.108309492  0.10220325
    ## 10   43 0.110428403 0.105244566        <NA> 0.108647685 0.102142812
    ## 11   45 0.106887426 0.110818579 0.111516749 0.107179289  0.10457923
    ## 12   55 0.101507799 0.105455229 0.104251537 0.106088762 0.103609078
    ## 13   59 0.103415696  0.10351346 0.100971886 0.108515848 0.104119779
    ## 14   65  0.11256305  0.11366025 0.112475164 0.111539121 0.111844573
    ## 15   67  0.11229141        <NA> 0.109758184        <NA> 0.109166863
    ## 16   69 0.114392996 0.104970251 0.109161136 0.107839858 0.107005326
    ## 17   72 0.106965463        <NA> 0.107266218 0.106665207        <NA>
    ## 18   75 0.108368094  0.10773377 0.105117512 0.106359342 0.105999842
    ## 19   76 0.110931307 0.109048068 0.106670279  0.10805051 0.111364424
    ## 20   77 0.107284617 0.106476261 0.112886515 0.101454474  0.10454377
    ## 21   78 0.113982537 0.110739736 0.113457585 0.111259357 0.108290955
    ## 22   86 0.108360583 0.102932875 0.106523976 0.104131568 0.101939043
    ## 23   87 0.113658986 0.110688998 0.112175174 0.107445684 0.103597297
    ## 24   89 0.106393057  0.10721245        <NA> 0.104814949 0.100291816
    ## 25  106 0.105380438 0.104828457        <NA> 0.101852464 0.104347845
    ## 26  109 0.107026721 0.107718021 0.104457501 0.100723304 0.100848092
    ## 27  120 0.106856079 0.111398319 0.103014244 0.106365255 0.103045743
    ## 28  123 0.108080327 0.112383506  0.11008691 0.107630692 0.101780509
    ## 29  132  0.10908984 0.108979186 0.106198191 0.105698988 0.102579378
    ## 30  146 0.111194981 0.111374948 0.113454429 0.109239435 0.108603552
    ## 31  149 0.108500622 0.110531747 0.110113935 0.106510401 0.106897608
    ## 32  166 0.105211298 0.106707617  0.10962918        <NA> 0.099377278
    ## 33  170  0.11478716 0.111734748 0.111511576 0.113622709  0.11056932
    ## 34  177 0.107080076 0.103880457 0.104338764 0.106399715 0.102465143
    ## 35  186 0.105429887        <NA>  0.10383885 0.106167129 0.107530159
    ## 36  202 0.108924204 0.103006361 0.103228003 0.102029846 0.100056292
    ## 37  218  0.11380286 0.115676631 0.112240869 0.110319531 0.110548777
    ## 38  226 0.113086843 0.110028856 0.110193695 0.107221396 0.105330637
    ## 39  229 0.110090355 0.114248533 0.111349647 0.107372297 0.108299128
    ## 40  230 0.108365352        <NA> 0.105863778 0.107323444 0.106788809
    ## 41  234 0.110521689 0.110988335 0.110318671 0.107334344 0.108868811
    ## 42  242 0.110615293 0.112466023 0.110543716 0.108457735 0.106649029
    ## 43  249 0.107875226 0.106120934 0.110522028  0.10443051 0.104297366
    ## 44  250 0.107287702 0.109043837 0.109596383 0.105458715  0.10294026
    ## 45  252 0.106002663 0.109438988 0.104734598 0.108832219 0.105513741
    ## 46  277 0.115712476        <NA> 0.111484023        <NA> 0.105341071
    ## 47  280  0.10701986        <NA> 0.102710675 0.104851778 0.103765772
    ## 48  283 0.113436336 0.106568976  0.11338643  0.10820706 0.114399611
    ## 49  286 0.111565534 0.108984251        <NA>  0.10878002 0.104227529
    ## 50  287 0.108545195 0.109804562 0.112595781 0.109277394 0.107288238
    ## 51  289 0.106628753        <NA> 0.111128361 0.105573514 0.108340662
    ## 52  292 0.112005473 0.111128689 0.110529628 0.107524069 0.111213884
    ## 53  297 0.112519791 0.107296829 0.109572724 0.107416099 0.105536131
    ## 54  301 0.112105184 0.110651703 0.112009448 0.106664043        <NA>
    ## 55  305 0.106575146 0.109139729 0.107237307 0.100797063 0.103960862
    ## 56  306 0.107617927  0.10549774 0.105779618 0.104030737 0.103597858
    ## 57  314 0.114488695 0.111534036 0.113995497 0.116064016 0.111072404
    ## 58  323 0.108951493 0.108156014 0.107161066 0.107789675 0.103367206
    ## 59  328 0.116053343 0.108732458 0.107981127 0.110412399 0.107545571
    ## 60  336 0.105515499 0.105559957 0.102679883  0.10569702  0.10640764
    ## 61  337 0.110234919 0.109115569 0.110457079 0.111424351 0.109695757
    ## 62  338 0.113154484 0.113866071 0.107875179 0.109168346 0.110056896
    ## 63  347 0.106142357 0.105404684 0.106038639 0.104798607 0.102539751
    ## 64  348 0.108953572 0.109108861  0.10913821 0.111055899 0.111664612
    ## 65  349 0.108418448        <NA> 0.107116982 0.101918841        <NA>
    ## 66  350 0.104448098 0.106251499 0.109105546 0.105341362 0.102666049
    ## 67  351 0.109113066 0.110681827 0.104622912 0.107114993  0.10775628
    ## 68  352 0.107347915 0.108997259 0.106503869 0.105619654        <NA>
    ## 69  355 0.104675217        <NA> 0.108340642        <NA> 0.105741631
    ## 70  365 0.108368155  0.11282099 0.109700177 0.103664695 0.104995131
    ## 71  366 0.109407468 0.110142355 0.108078589 0.104223474 0.103784985
    ## 72  369 0.111860082 0.104362159 0.112709888 0.107915913 0.107131432
    ## 73  373  0.11218911 0.117060394 0.113077811 0.116411516 0.106141346
    ## 74  377 0.108737385 0.107877634 0.107528215 0.105783551 0.104676513
    ## 75  379 0.112029532 0.112141415        <NA> 0.109489517 0.111288052
    ## 76  380 0.111158847 0.104560429 0.106822683 0.104961175 0.109506164
    ## 77  398 0.111776578 0.107324817        <NA> 0.111445759 0.108830555
    ## 78  400 0.114692751 0.112106311        <NA> 0.108426877 0.107638328
    ## 79  408 0.110779441  0.11081594 0.111759647  0.10560759  0.11096394
    ## 80  409 0.109306118 0.109355444 0.104203305 0.104801719 0.104392625
    ## 81  416 0.111767429 0.109024281 0.113209208 0.105000017 0.106021985
    ## 82  417 0.109277104  0.10508806 0.105360371 0.105517925  0.10132809
    ## 83  419 0.114644146 0.108243592 0.112268963 0.106069914  0.10415295
    ## 84  423 0.108118705 0.107796862 0.107986282 0.103578995  0.11011534
    ## 85  424 0.107988193  0.10727975        <NA> 0.107820109 0.107154515
    ## 86  426 0.110310062 0.106626194 0.105759193 0.108039787 0.105913739
    ## 87  431 0.117180111 0.110687702 0.107133996  0.10872562 0.106799552
    ## 88  440 0.108088699  0.10864704 0.108510511        <NA> 0.103824334
    ## 89  442 0.107946154 0.114161562   0.1105537 0.106454629 0.103088929
    ## 90  448 0.109258188 0.105841078 0.107747641        <NA>  0.10382381
    ## 91  449 0.106108076 0.106946238 0.109820109        <NA> 0.108115146
    ## 92  452 0.108803351        <NA> 0.107040939 0.108567858 0.105120602
    ## 93  453 0.113857033 0.112321772 0.108314519 0.109028408 0.106029713
    ## 94  471 0.111027383 0.106424715 0.111068422 0.107208238 0.110534005
    ## 95  484  0.11139422 0.110936838 0.109182887 0.110607585 0.107057538
    ## 96  485 0.106042813 0.105158363 0.107758828 0.107281321 0.106181816
    ## 97  486 0.109161071 0.114634379        <NA> 0.110035156 0.107234758
    ## 98  487 0.110821971 0.107791347 0.109855229 0.110951271 0.105861634
    ## 99  488 0.110418756 0.111994328 0.113132987 0.108902038 0.109449907
    ## 100 489  0.11477384 0.113322128 0.115109381 0.116004489 0.112260161
    ## 101 490 0.111762756 0.109627815 0.111492905 0.110104053        <NA>
    ## 102 491 0.116934974 0.113763228 0.111358448 0.110509854 0.110541984
    ## 103 492 0.109757685 0.109912273 0.110672861 0.109064952 0.109161341
    ## 104 493 0.108357146 0.108161281 0.109491179 0.104448142 0.108636703
    ## 105 494 0.116669151 0.109711076 0.112133216 0.111399722 0.108836759
    ## 106 495          Na 0.105142354 0.108149625 0.105918659 0.102512562

There are 106 people that are in amyloid but not in baseline

``` r
mci_combined = 
  inner_join(mci_data, amyloid_df, by = "id")
```

There are 381 observations and 11 variables left in the combined file.

``` r
write_csv(mci_combined, "data_mci/mci_combined.csv")
```
